In [1]:
from PIL import Image
# from transformers import BertModel, BertConfig, BertTokenizer, ViTConfig, ViTImageProcessor, ViTModel, VisionEncoderDecoderConfig, VisionEncoderDecoderModel
# from transformers import SiglipImageProcessor, SiglipVisionModel, SiglipTokenizer, SiglipTextModel, SiglipProcessor, SiglipModel
from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection, CLIPTokenizer, CLIPTextModelWithProjection, CLIPProcessor, CLIPModel
import torch

# vision_processor = SiglipImageProcessor.from_pretrained("google/siglip-base-patch16-224")
# vision_model = SiglipVisionModel.from_pretrained("google/siglip-base-patch16-224")
# joint_processor = SiglipProcessor.from_pretrained("google/siglip-base-patch16-224")

# tokenizer = SiglipTokenizer.from_pretrained("google/siglip-base-patch16-224")
# text_model = SiglipTextModel.from_pretrained("google/siglip-base-patch16-224")
# joint_model = SiglipModel.from_pretrained("google/siglip-base-patch16-224")

vision_processor = CLIPImageProcessor.from_pretrained("openai/clip-vit-base-patch32")
vision_model = CLIPVisionModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
joint_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-base-patch32")
text_model = CLIPTextModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
joint_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

device = "cuda" if torch.cuda.is_available() else "cpu"

# config_encoder = ViTConfig.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
# config_decoder = BertConfig.from_pretrained("google-bert/bert-base-uncased")

# config = VisionEncoderDecoderConfig.from_encoder_decoder_configs(config_encoder, config_decoder)

# vision_model = VisionEncoderDecoderModel(config=config)
# vision_model = ViTModel(config=config_encoder)
# text_model = BertModel(config=config_decoder)

# tokenizer = BertTokenizer.from_pretrained("google-bert/bert-base-uncased")
# image_processor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

# vision_model.config.decoder_start_token_id = tokenizer.cls_token_id
# vision_model.config.pad_token_id = tokenizer.pad_token_id

/Users/jeremy.herzog/.pyenv/versions/3.11.4/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [9]:
# text = "a soccer player scoring a goal"
text = "a group of soccer players entering a stadium"
# text = "a crowd of people standing around a soccer ball"
# text = 'a crowd of people watching a soccer game'
# encoded_input = tokenizer(text, return_tensors='pt')
# text_output = text_model(**encoded_input)
# text_output.pooler_output

# encoded_text_input = tokenizer([text],return_tensors="pt",padding="max_length")
with torch.no_grad():
    encoded_text_input = tokenizer([text],return_tensors="pt",padding=True)
    text_output = text_model(**encoded_text_input)
    # text_output.pooler_output
text_output.text_embeds

tensor([[ 4.5665e-02, -3.3157e-01, -1.6029e-01,  1.2278e-01, -2.9528e-01,
          3.0222e-01,  5.4669e-02, -1.6842e-01, -4.8415e-01, -1.2492e-01,
         -1.9694e-01, -3.1356e-01, -1.0261e-01, -4.4654e-02,  5.8088e-02,
         -3.6037e-02, -4.1642e-01,  3.5602e-01, -3.1593e-01,  3.3154e-01,
          1.4510e-01,  1.3596e-01,  2.4697e-01, -5.6287e-01, -2.1235e-01,
          2.3449e-02,  9.9695e-03,  3.8866e-01,  1.7823e-01, -1.9681e-01,
          3.8699e-01,  9.3136e-02,  2.8987e-01, -3.6271e-01, -8.2478e-01,
         -9.8939e-02,  9.6650e-02,  1.8529e-02,  4.7539e-02,  7.5204e-02,
         -5.8159e-02,  5.0336e-02,  1.7066e-01,  2.3328e-01, -2.5723e-02,
          2.5519e-01, -1.2281e-01, -2.9611e-01,  1.5704e-01, -3.9208e-01,
         -1.3305e-01, -7.5586e-02, -1.4631e-01, -2.5728e-01, -9.3259e-03,
          7.3546e-03,  5.7894e-02,  3.9526e-01, -1.5436e-01,  1.0147e-01,
          5.4457e-01,  1.8206e-01,  2.7774e-01,  1.3705e-01, -1.9786e-01,
         -1.3216e-02,  2.9700e-03,  5.

In [7]:
with Image.open("../outputs/frames/frame1.png") as frame_a, Image.open("../outputs/frames/frame2.png") as frame_b:
    encoded_image_input = vision_processor(images=[frame_a, frame_b], return_tensors="pt")
    print("encoded images:", encoded_image_input['pixel_values'])

    with torch.no_grad():
        # print(encoded_image_input)
        # image_outputs = encoded_image_input.pixel_values
        image_outputs = vision_model(**encoded_image_input)

image_outputs.image_embeds

encoded images: tensor([[[[-0.6536, -0.5076, -0.4200,  ..., -0.5076, -0.5222, -0.3908],
          [-0.7704, -0.6682, -0.7850,  ..., -0.6536, -0.4784, -0.4200],
          [-0.7412, -0.8142, -1.0769,  ..., -1.0039, -1.0331, -0.6682],
          ...,
          [-1.1207, -1.1061, -1.1207,  ..., -1.1207, -1.1207, -1.1207],
          [-1.1353, -1.1207, -1.1353,  ..., -1.1061, -1.1061, -1.1061],
          [-1.1499, -1.1645, -1.1499,  ..., -1.0769, -1.0915, -1.0915]],

         [[-0.5815, -0.4314, -0.4464,  ..., -0.5665, -0.5215, -0.4314],
          [-0.7016, -0.6115, -0.8066,  ..., -0.7016, -0.4764, -0.4764],
          [-0.6715, -0.7466, -1.0617,  ..., -1.0767, -1.0767, -0.7766],
          ...,
          [-0.6865, -0.6565, -0.6865,  ..., -0.7466, -0.7466, -0.7466],
          [-0.6715, -0.6715, -0.7016,  ..., -0.7316, -0.7316, -0.7316],
          [-0.7016, -0.7166, -0.7016,  ..., -0.7016, -0.7166, -0.7166]],

         [[-0.0724,  0.0698,  0.0129,  ..., -0.1720, -0.2431, -0.1435],
          [-0.

tensor([[ 0.2456,  0.0431,  0.0671,  ..., -0.2348,  0.8446,  0.3799],
        [-0.0497,  0.0269, -0.1300,  ...,  0.0662,  0.7740,  0.2374]])

In [10]:
with Image.open("../outputs/frames/frame1.png") as frame:
    # important: we pass `padding=max_length` since the model was trained with this
    # joint_inputs = joint_processor(text=["soccer stadium"], images=[frame], padding="max_length", return_tensors="pt")
    joint_inputs = joint_processor(text=["soccer stadium"], images=[frame], padding="max_length", return_tensors="pt")

    with torch.no_grad():
        joint_outputs = joint_model(**joint_inputs)

joint_outputs

Unused or unrecognized kwargs: padding.


CLIPOutput(loss=None, logits_per_image=tensor([[19.8296]]), logits_per_text=tensor([[19.8296]]), text_embeds=tensor([[-2.2368e-03, -3.7621e-02, -6.3098e-03, -2.5923e-02,  5.3038e-03,
          1.8363e-02, -3.8270e-03, -6.2317e-02, -2.1765e-02,  3.1731e-02,
         -4.2252e-02, -3.1592e-02, -2.7623e-02, -1.1590e-03, -1.0580e-02,
          8.6438e-03,  3.3055e-02,  1.1662e-02, -4.7116e-02, -9.7702e-03,
          4.6666e-02,  1.8993e-02,  1.3469e-02, -1.4681e-02, -5.1221e-02,
         -1.3784e-02, -1.1290e-02,  1.0305e-02, -1.3452e-02,  1.7552e-03,
         -9.5011e-03,  7.3325e-04,  1.1213e-02, -1.2532e-02, -5.0384e-02,
          1.3685e-02,  1.7044e-02,  4.8416e-03, -1.4401e-02,  9.6888e-03,
         -2.8014e-02,  8.3925e-03,  5.5132e-02,  3.0326e-02, -7.7079e-03,
          1.8108e-03,  1.6311e-02, -4.4262e-02,  1.1711e-02, -2.7436e-02,
         -2.0077e-02, -8.9569e-03,  1.1319e-02,  6.1743e-03, -7.6811e-03,
         -1.6515e-02,  4.9277e-03,  1.3442e-02, -4.7543e-02,  3.1525e-02,
   

In [5]:
def cos_sim(emb_1, emb_2):
    return dot(emb_1, emb_2) / (norm(emb_1) * norm(emb_2))

In [11]:
from numpy.linalg import norm
from numpy import dot

# emb_1 = text_output.pooler_output.detach().numpy()[0]
# emb_2 = image_outputs.detach().numpy()[0]
text_emb = text_output.text_embeds.detach().numpy()[0]
img_emb_1, img_emb_2 = image_outputs.image_embeds.detach().numpy()

# image_arr = image_embeddings / norm(image_embeddings, axis=0)
# image_arr.min(), image_arr.max()

# dot(emb_1, image_outputs.pooler_output.detach().numpy())

cos_sim(text_emb, img_emb_1)
# cos_sim(img_emb_1, img_emb_2)

0.25182277

In [12]:
text_emb = joint_outputs.text_embeds.detach().numpy()[0]
img_emb = joint_outputs.image_embeds.detach().numpy()[0]

print("joint cos sim:", cos_sim(text_emb, img_emb))

logits_per_image = joint_outputs.logits_per_image  # this is the image-text similarity score
print(logits_per_image)

joint cos sim: 0.19829638
tensor([[19.8296]])


In [ ]:
from transformers import VisionEncoderDecoderModel, AutoTokenizer, ViTImageProcessor

max_length = 16
num_beams = 4
gen_kwargs = {"max_length": max_length, "num_beams": num_beams}

generator_processor = ViTImageProcessor.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
generator_model = VisionEncoderDecoderModel.from_pretrained("nlpconnect/vit-gpt2-image-captioning")
generator_tokenizer = AutoTokenizer.from_pretrained("nlpconnect/vit-gpt2-image-captioning")

with Image.open("../outputs/frames/frame1.png") as img:
    if img.mode != "RGB":
      img = i_image.convert(mode="RGB")

    # pixel_values = vision_processor(images=[img], return_tensors="pt").pixel_values
    pixel_values = generator_processor(images=[img], return_tensors="pt").pixel_values
    print(pixel_values)
    # pixel_values = pixel_values.to(device)

    output_ids = generator_model.generate(pixel_values, **gen_kwargs)

output_ids

In [ ]:
preds = generator_tokenizer.batch_decode(output_ids, skip_special_tokens=True)
[pred.strip() for pred in preds]

In [20]:
import glob
import os

files = sorted(glob.glob("../outputs/frames/frame*.png"), key=lambda file: int(os.path.basename(file).replace("frame", "").replace(".png", "")))
files

['../outputs/frames/frame1.png',
 '../outputs/frames/frame2.png',
 '../outputs/frames/frame3.png',
 '../outputs/frames/frame4.png',
 '../outputs/frames/frame5.png',
 '../outputs/frames/frame6.png',
 '../outputs/frames/frame7.png',
 '../outputs/frames/frame8.png',
 '../outputs/frames/frame9.png',
 '../outputs/frames/frame10.png',
 '../outputs/frames/frame11.png',
 '../outputs/frames/frame12.png',
 '../outputs/frames/frame13.png',
 '../outputs/frames/frame14.png',
 '../outputs/frames/frame15.png',
 '../outputs/frames/frame16.png',
 '../outputs/frames/frame17.png',
 '../outputs/frames/frame18.png',
 '../outputs/frames/frame19.png',
 '../outputs/frames/frame20.png',
 '../outputs/frames/frame21.png',
 '../outputs/frames/frame22.png',
 '../outputs/frames/frame23.png',
 '../outputs/frames/frame24.png',
 '../outputs/frames/frame25.png',
 '../outputs/frames/frame26.png',
 '../outputs/frames/frame27.png',
 '../outputs/frames/frame28.png',
 '../outputs/frames/frame29.png',
 '../outputs/frames/fra

In [31]:
from datetime import timedelta

for i in range(1, len(files)):
    with Image.open(files[i-1]) as frame_1, Image.open(files[i]) as frame_2:
        encoded_image_input = vision_processor(images=[frame_1, frame_2], return_tensors="pt")
    
        with torch.no_grad():
            # print(encoded_image_input)
            # image_outputs = encoded_image_input.pixel_values
            frame_1_emb, frame_2_emb = vision_model(**encoded_image_input).image_embeds.detach().numpy()
            print(timedelta(seconds=(8/25)*i), cos_sim(frame_1_emb, frame_2_emb))

0:00:00.320000 0.91292214
0:00:00.640000 0.9254499
0:00:00.960000 0.90178657
0:00:01.280000 0.8833782
0:00:01.600000 0.9435634
0:00:01.920000 0.8976178
0:00:02.240000 0.90891844
0:00:02.560000 0.9089523
0:00:02.880000 0.91062534
0:00:03.200000 0.921466
0:00:03.520000 0.9291304
0:00:03.840000 0.9195519


KeyboardInterrupt: 